name: omni
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openjdk=8
  - orekit==12.1.2
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - jupyterlab
  - ipykernel
  - opencv==4.10.0
  - pyserial
  - websockets==11.0.3
  - pillow
  - pip:
      - git+https://gitlab.orekit.org/orekit/orekit-data.git
      - openpyxl
      - casadi
      - TauLidarCamera
      - pyrealsense2